# Generated by Django 5.2.1 on 2025-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={
                "ordering": ["name"],
                "verbose_name": "Task type",
                "verbose_name_plural": "Task types",
            },
        ),
    ]
